// auth
export const SET_AUTH = "SET_AUTH";

// user
export const SET_USER = "SET_USER";

// payment
export const UPDATE_PAYMENT_MODEL = "UPDATE_PAYMENT_MODEL";
export const SET_PAYMENT_SCHEDULE = "SET_PAYMENT_SCHEDULE";
export const UPDATE_PAYMENT_SCHEDULE_DAY = "UPDATE_PAYMENT_SCHEDULE_DAY";
export const EMPTY_PAYMENT_SCHEDULE = "EMPTY_PAYMENT_SCHEDULE";
